<?php

declare(strict_types=1);

namespace Nicholass003\LittleBrother\libs\_b0de35f4ce02f1ac\Nicholass003\Axiom\Enum;

enum MemoryCategory : int{

    case INVALID = -1;
    case UNKNOWN = 0;
	case INVALID_SIZE_UNKNOWN = 1;
	case ACTOR = 2;
	case ACTOR_ANIMATION = 3;
	case ACTOR_RENDERING = 4;
	case BALANCER = 5;
	case BLOCK_TICKING_QUEUES = 6;
	case BIOME_STORAGE = 7;
	case CEREAL = 8;
	case CIRCUIT_SYSTEM = 9;
	case CLIENT = 10;
	case COMMANDS = 11;
	case DB_STORAGE = 12;
	case DEBUG = 13;
	case DOCUMENTATION = 14;
	case ECS_SYSTEMS = 15;
	case FMOD = 16;
	case FONTS = 17;
	case IM_GUI = 18;
	case INPUT = 19;
	case JSON_UI = 20;
	case JSON_UI_CONTROL_FACTORY_JSON = 21;
	case JSON_UI_CONTROL_TREE = 22;
	case JSON_UI_CONTROL_TREE_CONTROL_ELEMENT = 23;
	case JSON_UI_CONTROL_TREE_POPULATE_DATA_BINDING = 24;
	case JSON_UI_CONTROL_TREE_POPULATE_FOCUS = 25;
	case JSON_UI_CONTROL_TREE_POPULATE_LAYOUT = 26;
	case JSON_UI_CONTROL_TREE_POPULATE_OTHER = 27;
	case JSON_UI_CONTROL_TREE_POPULATE_SPRITE = 28;
	case JSON_UI_CONTROL_TREE_POPULATE_TEXT = 29;
	case JSON_UI_CONTROL_TREE_POPULATE_TTS = 30;
	case JSON_UI_CONTROL_TREE_VISIBILITY = 31;
	case JSON_UI_CREATE_UI = 32;
	case JSON_UI_DEFS = 33;
	case JSON_UI_LAYOUT_MANAGER = 34;
	case JSON_UI_LAYOUT_MANAGER_REMOVE_DEPENDENCIES = 35;
	case JSON_UI_LAYOUT_MANAGER_INIT_VARIABLE = 36;
	case LANGUAGES = 37;
	case LEVEL = 38;
	case LEVEL_STRUCTURES = 39;
	case LEVEL_CHUNK = 40;
	case LEVEL_CHUNK_GEN = 41;
	case LEVEL_CHUNK_GEN_THREAD_LOCAL = 42;
	case NETWORK = 43;
	case MARKETPLACE = 44;
	case MATERIAL_DRAGON_COMPILED_DEFINITION = 45;
	case MATERIAL_DRAGON_MATERIAL = 46;
	case MATERIAL_DRAGON_RESOURCE = 47;
	case MATERIAL_DRAGON_UNIFORM_MAP = 48;
	case MATERIAL_RENDER_MATERIAL = 49;
	case MATERIAL_RENDER_MATERIAL_GROUP = 50;
	case MATERIAL_VARIATION_MANAGER = 51;
	case MOLANG = 52;
	case ORE_UI = 53;
	case PERSONA = 54;
	case PLAYER = 55;
	case RENDER_CHUNK = 56;
	case RENDER_CHUNK_INDEX_BUFFER = 57;
	case RENDER_CHUNK_VERTEX_BUFFER = 58;
	case RENDERING = 59;
	case RENDERING_LIBRARY = 60;
	case REQUEST_LOG = 61;
	case RESOURCE_PACKS = 62;
	case SOUND = 63;
	case SUB_CHUNK_BIOME_DATA = 64;
	case SUB_CHUNK_BLOCK_DATA = 65;
	case SUB_CHUNK_LIGHT_DATA = 66;
	case TEXTURES = 67;
	case VR = 68;
	case WEATHER_RENDERER = 69;
	case WORLD_GENERATOR = 70;
	case TASKS = 71;
	case TEST = 72;
	case SCRIPTING = 73;
	case SCRIPTING_RUNTIME = 74;
	case SCRIPTING_CONTEXT = 75;
	case SCRIPTING_CONTEXT_BINDINGS_MC = 76;
	case SCRIPTING_CONTEXT_BINDINGS_GT = 77;
	case SCRIPTING_CONTEXT_RUN = 78;
	case DATA_DRIVEN_UI = 79;
	case DATA_DRIVEN_UI_DEFS = 80;

    public static function safe(int $value) : self{
        return self::tryFrom($value) ?? self::UNKNOWN;
    }
}